<?php 
/**
 * Frontpage Slideshow
 * Slideshow creator for displaying in shop's main page
 *
 * @package slideshow
 * @author Vassilios Barzokas <contact@vbarzokas.com> 
 * @author website www.vbarzokas.com
 * @copyright Copyright 2011 Vassilios Barzokas
 * @license http://www.gnu.org/copyleft/gpl.html   GNU Public License V2.0
 * @version $Id: frontpage_slideshow.php 2.0 2013-04-10 17:50:04Z $
 */
?>
<script type="text/javascript">
		$(document).ready(function(){   
                    $("#slider").flexslider({
                        namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
                        selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
                        animation: "<?php echo FRONTPAGE_SLIDESHOW_ANIMATION_TYPE; ?>",              //String: Select your animation type, "fade" or "slide"
                        easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
                        direction: "<?php echo FRONTPAGE_SLIDESHOW_ORIENTATION; ?>",        //String: Select the sliding direction, "horizontal" or "vertical"
                        reverse: false,                 //{NEW} Boolean: Reverse the animation direction
                        animationLoop: <?php echo FRONTPAGE_SLIDESHOW_CONTINUOUS; ?>,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
                        smoothHeight: false,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode  
                        startAt: <?php echo FRONTPAGE_SLIDESHOW_STARTFROM; ?>,                     //Integer: The slide that the slider should start on. Array notation (0 = first slide)
                        slideshow: <?php echo FRONTPAGE_SLIDESHOW_AUTO; ?>,                //Boolean: Animate slider automatically
                        slideshowSpeed: <?php echo FRONTPAGE_SLIDESHOW_PAUSE; ?>,           //Integer: Set the speed of the slideshow cycling, in milliseconds
                        animationSpeed: <?php echo FRONTPAGE_SLIDESHOW_ANIM_DURATION; ?>,            //Integer: Set the speed of animations, in milliseconds
                        initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
                        randomize: false,               //Boolean: Randomize slide order

                        // Usability features
                        pauseOnAction: true,            //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
                        pauseOnHover: false,            //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
                        useCSS: true,                   //{NEW} Boolean: Slider will use CSS3 transitions if available
                        touch: true,                    //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
                        video: false,                   //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches

                        // Primary Controls
                        controlNav: <?php if(FRONTPAGE_SLIDESHOW_THUMBNAILS == 'thumbnails'){echo '"thumbnails"';}else if(FRONTPAGE_SLIDESHOW_THUMBNAILS == 'circles'){ echo '"circles"';}else{echo 'false';}?>,               //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
                        directionNav: <?php echo FRONTPAGE_SLIDESHOW_NAV; ?>,             //Boolean: Create navigation for previous/next navigation? (true/false)
                        prevText: "Previous",           //String: Set the text for the "previous" directionNav item
                        nextText: "Next",               //String: Set the text for the "next" directionNav item

                        // Secondary Navigation
                        keyboard: true,                 //Boolean: Allow slider navigating via keyboard left/right keys
                        multipleKeyboard: false,        //{NEW} Boolean: Allow keyboard navigation to affect multiple sliders. Default behavior cuts out keyboard navigation with more than one slider present.
                        mousewheel: false,              //{UPDATED} Boolean: Requires jquery.mousewheel.js (https://github.com/brandonaaron/jquery-mousewheel) - Allows slider navigating via mousewheel
                        pausePlay: false,               //Boolean: Create pause/play dynamic element
                        pauseText: 'Pause',             //String: Set the text for the "pause" pausePlay item
                        playText: 'Play',               //String: Set the text for the "play" pausePlay item

                        // Special properties
                        controlsContainer: "",          //{UPDATED} Selector: USE CLASS SELECTOR. Declare which container the navigation elements should be appended too. Default container is the FlexSlider element. Example use would be ".flexslider-container". Property is ignored if given element is not found.
                        manualControls: "",             //Selector: Declare custom control navigation. Examples would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
                        sync: "",                       //{NEW} Selector: Mirror the actions performed on this slider with another slider. Use with care.
                        asNavFor: "",                   //{NEW} Selector: Internal property exposed for turning the slider into a thumbnail navigation for another slider

                        // Carousel Options
                        itemWidth: 0,                   //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
                        itemMargin: 0,                  //{NEW} Integer: Margin between carousel items.
                        minItems: 0,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
                        maxItems: 0,                    //{NEW} Integer: Maxmimum number of carousel items that should be visible. Items will resize fluidly when above this limit.
                        move: 0,                        //{NEW} Integer: Number of carousel items that should move on animation. If 0, slider will move all visible items.
                        start: function(slider){
                          $('body').removeClass('loading');
                        }
                     });
                                
	   });     
</script>

<style type="text/css">
</style>

<?php     
			$slideshow_query = "SELECT * FROM " . TABLE_SLIDESHOW;
			$slideshow_result = $db->Execute($slideshow_query);
			if(FRONTPAGE_SLIDESHOW_STATUS == 'true') {
?>
            <div  id="slider"  class="flexslider">
                <ul  class="slides">        
                    <?php 
                    
                    while(!$slideshow_result->EOF)
                    {
                    ?>
                            <li data-thumb="<?php  echo $template->get_template_dir('',DIR_WS_TEMPLATE, $current_page_base,'images').'/slideshow/'.$slideshow_result->fields['image']; ?>">
                                <?php if (FRONTPAGE_SLIDESHOW_LINKSLIDES == 'true'){?>
                                  <a href="<?php echo $slideshow_result->fields['url']; ?>">
                                <?php } ?>
                                    <img src="<?php  echo $template->get_template_dir('',DIR_WS_TEMPLATE, $current_page_base,'images').'/slideshow/'.$slideshow_result->fields['image']; ?>"   alt="slide image" />
                                    <?php if(FRONTPAGE_SLIDESHOW_SHOW_CAPTION == 'true'){ ?>
                                        <p class="flex-caption"><?php echo $slideshow_result->fields['caption']?></p>    
                                    <?php } ?>
                                <?php if (FRONTPAGE_SLIDESHOW_LINKSLIDES == 'true'){?>
                                  </a>
                                <?php } ?>
                            </li>
                    <?php 
                    $slideshow_result->MoveNext();
                    } //end while
                    ?>
                </ul>
        </div>     
<?php } ?>